### ISSUE TITLE
Semester info in clips

### ISSUE THREAD

**Issue by paradite** [bsmmoon/KBMP#28]
Can I get semester info in clips for better prioritization of modules?
For example, before semester 4, I would not list level 4 modules as available.

**Comment by bsmmoon** [comment]
But semester is not absolute right now because we only ask for how many semester left. So semester 4 does not necessarily mean 4th semester. Even semester 1 can be 4th semester. Shall we change our semester to be absolute instead of relative?

**Comment by paradite** [comment]
Okay. nvm. I will find another way to decide based on modules already taken and planned.
