### ISSUE TITLE
Module classification

### ISSUE THREAD

**Issue by bsmmoon** [bsmmoon/KBMP#3]
Computer Science Foundation
Computer Science Breadth and Depth
etc.

**Comment by bsmmoon** [comment]
One module can have multiple classifications.
For example, internship is usually CSBreadth&Depth but if ATAP is taken as well it becomes UE.
Therefore the slot has to be multislot STRING.

**Comment by paradite** [comment]
We only need the modules to have the classification of "foundation" or "non-foundation". then the breath&depth we can internally assign by looking at if the module code starts with CS.

**Comment by paradite** [comment]
@joey-c we also need the project modules to be classified.
i.e. softwareproject, thematicproject, mediaproject, etc...
