### ISSUE TITLE
Focus Area module info into clips

### ISSUE THREAD

**Issue by bsmmoon** [bsmmoon/KBMP#30]

**Comment by paradite** [comment]
@bsmmoon actually there's an easy way of doing this:
when user select a focus area, in Java u know the modules in primary and electives for that focus area. So u can simply assert the facts like 
(primaryfocus CS3230)
(electivefocus CS4444)
then I will have rules in clips to catch them and modify the template, also recalculating the score.

**Comment by bsmmoon** [comment]
but focus area has `primary`, `electives`, and `unrestricted electives`.

what about template like `(primaryfocus (primaries <modules>) (electives <modules>) (nonblabla <modules))` and `(electivefocus <same stuffs>)`?

**Comment by paradite** [comment]
@bsmmoon look at: http://www.comp.nus.edu.sg/programmes/ug/focus/
there's only `primary` and `elective`
also we do not need to differentiate different focus areas in clips. they all have same weight.

**Comment by paradite** [comment]
@bsmmoon 

```
(primaryfocus CS3230 CS3333)
(electivefocus CS4444 CS5555)
```

is sufficient

**Comment by bsmmoon** [comment]
@paradite http://www.comp.nus.edu.sg/programmes/ug/focus/#SWEngrg Software Engineering and one more other have `unrestricted electives`.

**Comment by bsmmoon** [comment]
oh i see your point. so all chosen focus area have the same importance eh. ok.

**Comment by paradite** [comment]
@bsmmoon ah, no need to care, just treat as elective

**Comment by paradite** [comment]
no need to make exception for two IS modules

**Comment by bsmmoon** [comment]
security also has. but i guess it's ok to put them in electives. not like someone will check all the corner cases :p

**Comment by paradite** [comment]
@bsmmoon yes, by not differentiating focus areas, we can also allow user to choose multiple focus areas, since they will end up together anyway, instead of only choosing primary and secondary.

**Comment by bsmmoon** [comment]
@paradite good point. approved haha

**Comment by paradite** [comment]
@bsmmoon also if you want to retain the unrestricted elective, you can simply assert them as a separate list, like
(unrestrictedfocus IS2222)

**Comment by bsmmoon** [comment]
I'll combine elec and non-elec and make it simpler. the page does not have much explanation on them anyway.

**Comment by bsmmoon** [comment]
String or Symbol?

**Comment by paradite** [comment]
@bsmmoon 
STRINGs
(electivefocus "CS4444" "CS5555")

**Comment by bsmmoon** [comment]
https://github.com/bsmmoon/KBMP/commit/735f1333a2e111d0bb94368d14a8d92b1b60e459
