### ISSUE TITLE
Ask user's background info in the beginning

### ISSUE THREAD

**Issue by paradite** [bsmmoon/KBMP#47]
This can be together with the "how many semesters left"
- How many semester have you left? (8 for freshmen)
  (by default the input field should have 8 auto-filled for convenience)
- Have you taken O Level H2 Maths or equivalent?
- Have you taken O Level H2 Physics or equivalent?
  @bsmmoon please provide corresponding APIs in backend to record this info, and pass the info to clips

**Comment by paradite** [comment]
Also, ask the user if he/she intend to do NOC/SIP/ATAP
For NOC/ATAP, need to specify semester
So the UI could be:
Do you intend to do Student Internship Program (SIP) during summer vacation?
Do you intend to do Advanced Technology Attachment Programme (ATAP)? Semester 口.
Do you intend to do 1-semester NUS Overseas College (NOC)? Semester 口.
Do you intend to do 1-year NUS Overseas College (NOC)? Semester 口 and Semester 口.
口 is for selection of sememster from 1 to 8. (will be changed to yearXSemY later)

**Comment by paradite** [comment]
Additional questions:
Do you have a strong maths background?
Are you exempted from CS2101 (CS communication module)?
@bsmmoon backend please provide corresponding APIs.

**Comment by paradite** [comment]
Additional question:
Which pair of CS 8MC project modules do you intend to take:
- Software Engineering Project (CS3201 and CS3202)
- Software Development on Evolving Platforms and Software Engineering on Modern Application Platforms (CS3216 and CS3217)
- Thematic Systems Project (CS3281 and CS3282)
- Media Technology Project (CS3283 and CS3284)

use assertions like:
logic.execute("(assert (softwareprojectnormal))");
variations:
(softwareprojectnormal)
(softwareprojectthematic)
(softwareprojectmedia)
(softwareprojectmodern)

I have added these lines in `Main.java` for your reference:

```
        logic.execute("(assert (softwareprojectnormal))");
//      logic.execute("(assert (softwareprojectthematic))");
```

@bsmmoon

**Comment by bsmmoon** [comment]
APIs added so far:
- assertGoodMath()
- assertNormalMath()
- assertCommunicationExcemption()
- assertCommunicationNotExcempted()
- assertH2Maths()
- assertH2Physics()
- assertSIP()
- asertATAP(int semester)
- assertNOC1Sem(int semester)
- assertNOC1Year(int semester)
- assertCS3201()
- assertCS3216()
- assertCS3281()
- assertCS3283()

**Comment by paradite** [comment]
@bsmmoon should be `exempted` not `Excepted`, also should be `exemption`

**Comment by bsmmoon** [comment]
Typo fixed

**Comment by xuruofan** [comment]
Completed
