### ISSUE TITLE
Show one module per row

### ISSUE THREAD

**Issue by bsmmoon** [bsmmoon/KBMP#50]

**Comment by paradite** [comment]
@xuruofan why is this close?

**Comment by paradite** [comment]
currently the module information is spread to 3 lines, can we condense them into 1 or 2 lines?
see the mockup I provided in whatsapp for reference:
![img-20160413-wa0012](https://cloud.githubusercontent.com/assets/1209810/14518741/8a21e59c-024c-11e6-996c-d63f11d743bc.jpg)

**Comment by xuruofan** [comment]
closed by mistake....
