### ISSUE TITLE
store internal semester number based on year X sem Y

### ISSUE THREAD

**Issue by paradite** [bsmmoon/KBMP#51]
The user should select to start planning from year X sem 1/sem 2
then we get the initial semester number as year_2 if it start from sem 1 or year_2+1 if start from sem 2
eg.
from year 3 sem 1, our internal semester number should be 2 \* 2 + 1 = 5
for year 3 sem 2, it should be 2 \* 2 + 2 = 6
we always assume there are 8 semester in total and the planning stops when we finish planning for semester 8.
I think this means logic also need to modify the APIs accordingly @bsmmoon

**Comment by paradite** [comment]
@bsmmoon this should be the priority now since it will allow us to filter module availability based on current semester inside clips.
the filtering by semester availability should be in clips as it is part of the KB-planning process.
also make sure the modules in clips template have an additional field to capture which semester it is offered. Maybe you can create a separate issue for that.

**Comment by bsmmoon** [comment]
@xuruofan 
Please checkout to `start_time` branch and finish the GUI part.
Instead of `setNumberOfSemestersLeft`, use `setStartTime(int year, int semester)`.

You need one more input field to get two integers of course.

**Comment by bsmmoon** [comment]
@xuruofan Never mind, I just did it.

**Comment by bsmmoon** [comment]
https://github.com/bsmmoon/KBMP/commit/9e15b2f34515da0305732558d2196fbfccf0234f

**Comment by bsmmoon** [comment]
https://github.com/bsmmoon/KBMP/commit/5fc39a18a152afcb595cdd6f5541b728a1bc4447

**Comment by paradite** [comment]
I believe this is done? can we close this? @bsmmoon

**Comment by xuruofan** [comment]
Done
