### ISSUE TITLE
Number of fake modules does not conform to graduation requirements

### ISSUE THREAD

**Issue by paradite** [bsmmoon/KBMP#57]
For our batch, it should be 
1 SS
2 GEM (1 Arts GEM and 1 Science GEM)
2 Breath
3 Science from list S1 S2

**Comment by bsmmoon** [comment]
https://github.com/bsmmoon/KBMP/commit/c39b4633bdbb8ce9a90d436fb93b2dea31103243

**Comment by bsmmoon** [comment]
related to #39
