### ISSUE TITLE
GUI background project module selection

### ISSUE THREAD

**Issue by paradite** [bsmmoon/KBMP#59]
For project module selection:
![screen shot 2016-04-14 at 11 43 43 am](https://cloud.githubusercontent.com/assets/1209810/14516502/40426b88-0236-11e6-8994-d0b9baa69224.png)
The selection checkbox should be radio box, i.e. the user must choose exactly one of them, cannot leave blank or select multiple.
By default we can set the selection to CS3201 CS3202

**Comment by xuruofan** [comment]
Done
