### ISSUE TITLE
Rule design / implementation

### ISSUE THREAD

**Issue by bsmmoon** [bsmmoon/KBMP#6]

**Comment by paradite** [comment]
this depends on #5

**Comment by bsmmoon** [comment]
I think CLIPS does not need to ask the user anything. It is Java's work. Instead, CLIPS should have a way to convey its status to Java.

ex. Stop at SELECT phase and return process to Java. Java see that CLIPS is at SELECT phase, asks user, and passes the value.

**Comment by paradite** [comment]
closed as general issue
