### ISSUE TITLE
year X sem Y selection box size

### ISSUE THREAD

**Issue by paradite** [bsmmoon/KBMP#60]
Currently the box is too small on Mac:
![screen shot 2016-04-14 at 11 47 10 am](https://cloud.githubusercontent.com/assets/1209810/14516553/bf103076-0236-11e6-80a1-40e58829c495.png)

**Comment by xuruofan** [comment]
try now?

**Comment by paradite** [comment]
still the same, we fix later during meeting
![screen shot 2016-04-14 at 2 07 28 pm](https://cloud.githubusercontent.com/assets/1209810/14518439/6b6cc510-024a-11e6-814b-68adcbad8edd.png)

**Comment by xuruofan** [comment]
Done
