### ISSUE TITLE
module info for NOC modules

### ISSUE THREAD

**Issue by paradite** [bsmmoon/KBMP#67]
For NOC modules, 
We have TR3202 `Start-up Internship Programme`, 12 MC
info on: https://nusmods.com/modules/TR3202
XX3000 can be called `NOC Semester 2 placeholder module`, which has 28 MC.
please set both modules initial status to `unavailable`

**Comment by paradite** [comment]
Same for ATAP module `CP3880`

**Comment by bsmmoon** [comment]
Both will be initially unavailable but will become available asap because there is no prerequisites.

**Comment by bsmmoon** [comment]
What's the semester for XX3000? Sem 2?

**Comment by paradite** [comment]
doesn't matter the prereqs and semester, once u set to `unavailable` it will not appear

**Comment by bsmmoon** [comment]
it cannot be done in Java, so will need to make clips rules for them.

**Comment by paradite** [comment]
what kind of rules? u are not even using them as clips modules right?

**Comment by bsmmoon** [comment]
i thought you wanted to add them in clips working memory as modules?

**Comment by paradite** [comment]
the modules `TR3202` and `CP3880` should have correct info but they didn't appear in java

**Comment by paradite** [comment]
i just need them to appear in java with correct info, doesn't matter if they are in clips, but for `TR3202` and `CP3880`, they are already in clips with correct info, but the info is not used in java.

**Comment by bsmmoon** [comment]
hmm i thought they are fake modules. ok i know where to fix then.

**Comment by paradite** [comment]
yeah, please add `XX3000` also

**Comment by bsmmoon** [comment]
XX3000 is a fake is it?

**Comment by paradite** [comment]
yes

**Comment by bsmmoon** [comment]
https://github.com/bsmmoon/KBMP/commit/af073eb11fdbbc180986c406fcace9e78f0eadb6
